### ISSUE TITLE
Readthedocs webhook isn't working

### ISSUE THREAD

**Issue by MichaelClerx** [OxfordRSE/template-project-python#2]
Let's fix this when we're at our desks and can access both accounts :-)

**Comment by martinjrobins** [comment]
think this is working now. Can you check @MichaelClerx ?

**Comment by MichaelClerx** [comment]
Sorry, still doesn't pick up on changes automatically!

**Comment by martinjrobins** [comment]
is the url you sent me the payload URL? I think I need this to make the webhook

From the docs:
For Payload URL, use the URL of the integration on Read the Docs, found on the the project’s Integrations Admin dashboard page

**Comment by martinjrobins** [comment]
yay, webhook working. closing

**Comment by MichaelClerx** [comment]
Yay!
